### ISSUE TITLE
(React) Add client-side user input validation

### ISSUE THREAD

**Issue by kankenny** [Kankenny/StreetEasier#73]
Add super simple client-side user input validation such as:
- required input length for all fields
- same input length for the password and confirmPassword
- use regex for the email address
- implement a user feedback based on whether their input is correct or not

**Comment by mitpancholi98** [comment]
Hi there, Can I go on with "yup" and "react-hook-form" for this ?
Somewhat connected to #76

**Comment by kankenny** [comment]
Greetings,

Feel free to use any appropriate tool for any problem. The client side input validation is that is required is listed on the first commend in this issue

**Comment by kankenny** [comment]
Forwarding my comment from the pull request to this issue: 

> @mitpancholi98 This is great and very much appreciated!

> However, my colleague @rintendou and I are wondering why the yup schema replaces firebase? I apologize for the question 
>as I have not encountered yup yep and I only thought that is a library for user input validations.
