### ISSUE TITLE
(React) Implement loading component

### ISSUE THREAD

**Issue by kankenny** [Kankenny/StreetEasier#84]

**Comment by adi-uchiha** [comment]
Hey there. I want to work on this issue.
Can you give details of the issue and how to solve it

**Comment by kankenny** [comment]
Greetings Adi, thanks for taking an interest to contribute. This issue will be fairly simple.

1.) Pick a loading spinner here https://tailwind-elements.com/docs/standard/components/spinners/
2.) Implement the spinner as a functional react component named 'LoadingSpinner.js'
3.) Style the color of the spinner using 'text-primary' which is a custom tailwind class
4.) You can save it in the src/components/ui folder

**Comment by adi-uchiha** [comment]
@Kankenny  Can you please add 'hacktoberfest' as a [topic](https://github.com/topics/hacktoberfest) to your repo
It will bring potential new contributors to this repo and this repo will be valid for hacktoberfest

Also mark all the issues as 'hacktoberfest'
If I fixed the issue correctly please merge my PR and mark this issue and my PR as 'hacktoberfest-accepted'

Thanks :)

> YOUR PR/MRS MUST BE IN A REPO TAGGED WITH THE “HACKTOBERFEST” TOPIC, OR BE LABELED “HACKTOBERFEST-ACCEPTED.”
> Hacktoberfest is now opt-in for maintainers, so only contribute to projects that indicate they’re looking for Hacktoberfest PR/MRs.
> 
> Once your PR/MR has passed this check, we won’t check this again (unless your PR/MR fails a check before this, such as it being marked as spammy).

**Comment by kankenny** [comment]
@adi-uchiha Thanks for the suggestions and for resolving this issue. I merged your pr and applied your suggestions
