### ISSUE TITLE
(JavaScript, React) Implement Sorting Feature to the Apartments List

### ISSUE THREAD

**Issue by kankenny** [Kankenny/StreetEasier#99]

**Comment by asamaiya00** [comment]
Hi @Kankenny , may I work on this? Please assign it to me

**Comment by kankenny** [comment]
@asamaiya00 Greetings Animesh,

Thanks for taking interest in this project. The goal is to implement a sorting function using the higher-order array sort function in JavaScript. We will sort by apartment (pricePerMonth) and another sort by apartment (numPeopleInterested). Let me know what you like to do.

Additional details:
- The data (apartments) to be sorted is an array of apartment objects with the following key-value pairs: `{
		address: 'Lorem ipsum dolor sit amet cons2ectetur adipisicing.',
		pricePerMonth: 123,
		numBedrooms: 1,
		numBathrooms: 3,
		zipCode: '10000',
		numPeopleInterested: 3,
		peopleInterested: {},
	},`
- The file to be edited is located in /src/components/sort/SoortingFunctions.js

**Comment by asamaiya00** [comment]
Sure, @Kankenny. I'll create the functions. 

What should be the order (ascending/ descending)? Or should we keep both?

**Comment by kankenny** [comment]
We can disregard and worry about ascending and descending sorts later on. Very good question though
